server:
  port: 21002
# 配置 Springdoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs       # OpenAPI 文档路径
  swagger-ui:
    path: /swagger-ui        # Swagger UI 路径
  show-actuator: true        # 如果项目集成了 Actuator，可以显示相关文档

# 自定义文档组和标题
springdoc.group-configs:
  - group: user-api         # 定义文档组名称
    paths-to-match: /api/user/** # 定义包含的路径
    packages-to-scan: com.pjz.review.controller # 定义扫描的包路径
# 日志配置
logging:
  level:
    com.pjz: info
    org.springframework: warn
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/review_system?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 2048711712P!
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: true
    # 用于存储迁移历史记录的表名, 默认: flyway_schema_history
    table: flyway_schema_history
    # 迁移脚本编码, 默认: UTF-8
    encoding: UTF-8
    # 当迁移数据库存在但没有元数据的表时，自动执行基准迁移，新建flyway_schema_history表
    baseline-on-migrate: true
    # 数据库迁移脚本的位置, 默认: classpath:db/migration    # 这里也支持文件系统路径，前缀：filesystem:
    locations:
      - classpath:db/migration